package jdbcdemo.dao;

import java.sql.Connection;
import java.sql.SQLException;

import jdbcdemo.dao.mappers.ResultSetMapper;
import jdbcdemo.dao.uow.UnitOfWork;
import jdbcdemo.domain.Accident;

public class AccidentRepository extends RepositoryBase<Accident> {

	AccidentRepository(Connection connection, ResultSetMapper<Accident> mapper, UnitOfWork uow) throws SQLException {
		super(connection, mapper, uow);
	}

	@Override
	protected void setupInsert(Accident accident) throws SQLException {
		insert.setInt(1, accident.getCarId());
		insert.setDate(2, accident.getDate());
		insert.setString(3, accident.getDescription());
	}

	@Override
	protected void setupUpdate(Accident accident) throws SQLException {
		update.setInt(1, accident.getCarId());
		update.setDate(2, accident.getDate());
		update.setString(3, accident.getDescription());
		update.setInt(4, accident.getId());
	}

	@Override
	protected String createTableSql() {
		return "CREATE TABLE accident(" + "id INT GENERATED BY DEFAULT AS IDENTITY," + "car_id INT," + "date DATE,"
				+ "description VARCHAR(70)" + ")";
	}

	@Override
	protected String updateSql() {
		return "UPDATE accident SET (car_id, date, description) = (?,?,?) WHERE id=?";
	}

	@Override
	protected String insertSql() {
		return "INSERT INTO accident(car_id, date, description) VALUES (?,?,?)";
	}

	@Override
	protected String tableName() {
		return "accident";
	}

}