package jdbcdemo.dao;

import java.sql.Connection;
import java.sql.SQLException;

import jdbcdemo.dao.mappers.ResultSetMapper;
import jdbcdemo.dao.uow.UnitOfWork;
import jdbcdemo.domain.Car;

public class CarRepository extends RepositoryBase<Car> {

	public CarRepository(Connection connection, ResultSetMapper<Car> mapper, UnitOfWork uow) throws SQLException {
		super(connection, mapper, uow);
	}

	@Override
	protected void setupInsert(Car car) throws SQLException {
		insert.setString(1, car.getBrand());
		insert.setString(2, car.getRegistration());
		insert.setInt(3, car.getOwnersId());
	}

	@Override
	protected void setupUpdate(Car car) throws SQLException {
		update.setString(1, car.getBrand());
		update.setString(2, car.getRegistration());
		update.setInt(3, car.getOwnersId());
		update.setInt(4, car.getId());
	}

	@Override
	protected String createTableSql() {
		return "CREATE TABLE car(" + "id INT GENERATED BY DEFAULT AS IDENTITY," + "brand VARCHAR(20),"
				+ "registration VARCHAR(10)," + "owners_id INT" + ")";
	}

	@Override
	protected String insertSql() {
		return "INSERT INTO car(brand,registration, owners_id) VALUES (?,?,?)";
	}

	@Override
	protected String updateSql() {
		return "UPDATE car SET (brand, registration, owners_id) = (?,?,?) WHERE id=?";
	}

	@Override
	protected String tableName() {
		return "car";
	}
}