package jdbcdemo.dao;

import java.sql.Connection;
import java.sql.SQLException;

import jdbcdemo.dao.mappers.ResultSetMapper;
import jdbcdemo.dao.uow.UnitOfWork;
import jdbcdemo.domain.Owner;

public class OwnerRepository extends RepositoryBase<Owner> {

	public OwnerRepository(Connection connection, ResultSetMapper<Owner> mapper, UnitOfWork uow) throws SQLException {
		super(connection, mapper, uow);
	}

	@Override
	protected void setupInsert(Owner owner) throws SQLException {
		insert.setString(1, owner.getName());
		insert.setString(2, owner.getSurname());
		insert.setInt(3, owner.getAge());
	}

	@Override
	protected void setupUpdate(Owner owner) throws SQLException {
		update.setString(1, owner.getName());
		update.setString(2, owner.getSurname());
		update.setInt(3, owner.getAge());
		update.setInt(4, owner.getId());
	}

	@Override
	protected String updateSql() {
		return "UPDATE owner SET (name, surname, age) = (?,?,?) WHERE id=?";
	}

	@Override
	protected String insertSql() {
		return "INSERT INTO owner(name,surname,age) VALUES (?,?,?)";
	}

	@Override
	protected String tableName() {
		return "owner";
	}

	@Override
	protected String createTableSql() {
		return "CREATE TABLE owner(" + "id INT GENERATED BY DEFAULT AS IDENTITY," + "name VARCHAR(20),"
				+ "surname VARCHAR(50)," + "age INT" + ")";
	}

}
